apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
type: Opaque
data:
  # The fix is adding '| toString' before '| b64enc'
  mongo-root-password: {{ .Values.mongodb.rootPassword | toString | b64enc | quote }}
  mongo-keyfile: {{ .Values.mongodb.keyFileContent | b64enc | quote }}
