apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
type: Opaque
data:
  mongo-root-password: {{ .Values.mongodb.rootPassword | b64enc | quote }}
  jwt-secret: {{ .Values.backend.jwtSecret | b64enc | quote }}
  mongo-keyfile: {{ .Values.mongodb.keyFileContent | quote }}